language: java
script: 
  - sudo apt-get install protobuf-compiler
  - git clone https://github.com/matozoid/javaparser.git && cd javaparser && mvn install -DskipTests
  - git clone https://git-wip-us.apache.org/repos/asf/crunch.git && cd crunch && mvn install -DskipTests
  - mvn clean install -DTRAVIS=true
